### ISSUE TITLE
Module: HTML_Parser

### ISSUE THREAD

**Issue by oliversauter** [WorldBrain/crawler#3]
## Goal:

Parsing the HTML code of every URL that has been identified as an article

## Input

Gets URL from django app from table `articles` where column `processed_html_parser`=`false``

## Output

- Gives a JSON file to django app with fields `url` and `html`, which saves `html`,  `processed_html_parser`=`timestamp` to table `articles`, where `url` = URL

## Technical Implementation

Here we can use newspaper3k or boilerpipe to parse the HTML code of a URL. 
As soon as we get banned by the domain, we route the URLs of that specific domain to *[Crawlera](http://scrapinghub.com/crawlera/)*

This way we avoid unnecessarily consuming the requests we can have at Crawlera. For most blogs and websites it should work just fine with our own crawlers.

Dont forget errorlogging of failed URLs, so we can reparse if necessary.

**Comment by arpitgogia** [comment]
>Gets URL from django app from table

How do I connect to the django app?

**Comment by oliversauter** [comment]
@hoshomoh does he have to go over the django app at all, or is it enough just directly connecting to the postgres db?

**Comment by hoshomoh** [comment]
@oliversauter @arpitgogia This would depend on how the Html Parser would be implemented. 
Would the Html Parser be a separate module/app or would it be built inside that Django app itself?

**Comment by oliversauter** [comment]
From my understanding it does not have to be inside the crawler, since it is a separate process which just takes all the unprocessed urls and then puts the html code into the DB. We just have to make sure, that it is running periodically (or we manually start it, after reviewing the cleaned urls (from #2)

If we want to have a periodical/manual trigger for letting it run, it makes sense to put it inside the django application, right?

What is your opinion on that @arpitgogia / @hoshomoh / @tobisanya? Where would the module make the most sense? Inside django, where it is triggered or as a separate module that triggers itself periodically?

**Comment by oliversauter** [comment]
I just had another idea regarding the html parser! I need the input of @vpolisky @arpitgogia @hoshomoh @tobisanya  here.

SO:

We already mentioned that scrapy as part of the linkchecker, parses the html code so it can extract the URLs in the code in order to continue the spidering. 

What we could do is to check if the currently parsed url fits the requirements defined in the article_detector module ( #2 ) and if so, save the parsed html code and the URL in the table `articles` + add the value `is_article`=`true` and `processed_article_detector=`false` to table `all_urls` for the currently parsed URL.

This would save us one step of parsing = less risk of getting banned and less computing power + it would not be necessary to develop the HTML parser afterall?

What do you think guys?

**Comment by hoshomoh** [comment]
I was going to say the same thing. But, then I don't think ```processed_article_detector``` is still useful in the ```all_urls``` table since we are bypassing the article_detector module. But, if there is still plan to build article_detector module then we can leave it.

**Comment by arpitgogia** [comment]
I think the HTML Parser module would be better if it were in a more direct sort of contact with the django app since it uses the same database. We can use ***Celery*** (http://www.celeryproject.org/) which allows scheduling of such tasks. We can set the interval as a day or 12 hours etc. I also thought that the HTML Parser can kick in whenever a specific number of **new links** are added to the database. That way it would be more dynamic as compared to a scheduled task. 
Continuing on @oliversauter 's new approach, it looks like that will save us from creating another module and would work in our favour. Just a thought, maybe maintaining modularity will help us in the long run 😅

**Comment by oliversauter** [comment]
@hoshomoh @arpitgogia yeah it might be unnecessary, on the other hand, what about the storage? Do we get a problem if we save the html file of each URL? or should we just save it for now and then decide later if we want to delete it for certain URLs?

in this case we could just store everything the spider (#1) produces to the `all_urls` table and then process it via the content_extractor ( #4 ) so that the content elements are stored in the `articles` table. 
This approach would save us the work on 2 modules ( #2 , #3 ) and everything would still be modular. 
Also we would not have the column `html` in `articles` BUT in `all_urls`.

**Comment by arpitgogia** [comment]
We have to save the **content** only for indexing right? That would suffice. Maybe there's a way we can delete the content after indexing it?

**Comment by oliversauter** [comment]
ok, then lets just store everything for now and if we see the need for it, we delete the unnecessary html codes to free up space. @arpitgogia then it makes sense, that you work on: #4 , the content extractor.
